name: Build and Test

env:
  WORKING_DIR: "src"
  TEST_DIR: "test"
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_n_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ${{ env.WORKING_DIR }}
      run: dotnet restore
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: dotnet build --no-restore
#    - name: Test
#      working-directory: ${{ env.TEST_DIR }}
#      run: dotnet test --no-build --verbosity normal
